language: c

compiler:
- gcc

install:
- sudo apt-get update -qq
- sudo apt-get install -qq -y texlive texlive-lang-german  texlive-latex-recommended  texlive-latex-extra

script:
  - make
  - make check

# # deployment:
# after_success:
# - ./deployment/deploy.sh
